Repository lincoln1883/space-x, pull requests merged in 2023-06, with the labels that each got.

#28 Fetch rockets and Render rockets list
  package-lock.json
  package.json
  src/components/Rocket.jsx
  src/components/Rockets.jsx
  src/index.js
  src/redux/rockets/rocketsSlice.js
  src/redux/store.js
Labels: Fetch data

#30 Profile page display.
  src/components/Profile.jsx
Labels: Display Selected Rockets

#31 Fetch and Display Missions Data with Redux Integration
  src/components/Missions.jsx
  src/redux/missions/missionsSlice.js
  src/redux/store.js
Labels: Fetch data

#32 Render List of Joined Missions on "My Profile" Page
  src/components/Profile.jsx
  src/redux/missions/missionsSlice.js
Labels: enhancement

#33 Component testing
  src/__mocks__/axios.js
  src/test/__snapshots__/navbar.test.js.snap
  src/test/__snapshots__/rockets.test.js.snap
  src/test/__snapshots__/rocketsPage.test.js.snap
  src/test/navbar.test.js
  src/test/rocket.test.js
  src/test/rockets.test.js
  src/test/rocketsPage.test.js
Labels: Testing

#36 Added component tests for mission
  package-lock.json
  package.json
  src/test/Missions.test.js
  src/test/Profile.test.js
  src/test/__snapshots__/Missions.test.js.snap
  src/test/__snapshots__/Profile.test.js.snap
  src/test/missionsSlice.test.js
Labels: Testing
